name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: 1//0gQL3nflnGtdxCgYIARAAGBASNwF-L9IrU24RiuEigyJAI2cz6rKwaxJJoyVC0rXUIUE3eNn1dn1h3i7yolJScI2DrB-135UePVY
      run: |
        firebase deploy --only hosting
